version: '3.8'

services:
  app:
    build:
      context: .docker/dev
      dockerfile: Dockerfile
    ports:
      - '42042:3000'
    env_file: .docker/dev/.env-back
    working_dir: /app
    volumes:
      - .:/app
